# PacketFlix network packet capture as a (streaming) service. This project
# requires the separate GhostWire project in order to discover network and
# container information.
version: "2.4"
services:
    # Our capture-as-a-Service ;)
    packetflix:
        image: 'packetflix'
        read_only: true
        command:
        - "--port=5001"
        - "--discovery-service=gostwire.ghost-in-da-box"
        - "--gw-port=5000"
        - "--proxy-discovery"
        # Please note: port remapping is only possible when using a separate
        # network namespace, but *NOT* when using the host's network
        # namespace. Also, remapping happens *OUTSIDE* the container, such as
        # in the host, not at the container's "encasing".
        ports:
            - "5001:5001"
        # Run as non-root user.
        user: "65534"
        security_opt:
            # The default Docker container AppArmor profile blocks namespace
            # discovery, due to reading from /proc/$PID/ns/* is considered to be
            # ptrace read/ready operations.
            - apparmor:unconfined

            # The default Docker container seccomp profile is adaptive and
            # throws wide open all gates when showing it your capabilities. The
            # default seccomp profile thus does not interfere. But we might want
            # to slightly curb the powers of CRAP_SYS_ADMIN and
            # CRAP_SYS_PTRACE...
            - seccomp:seccomp/packetflix.json
        # In order to set only exactly a specific set of capabilities without
        # any additional Docker container default capabilities, we need to drop
        # "all" capabilities. Regardless of the order (there ain't one) of YAML
        # dictionary keys, Docker carries out dropping all capabilities first,
        # and only then adds capabilities. See also:
        # https://stackoverflow.com/a/63219871.
        cap_drop:
            - ALL
        cap_add:
            - SYS_ADMIN       # change namespaces
            - SYS_CHROOT      # change mount namespaces
            - SYS_PTRACE      # access nsfs namespace information
            - DAC_READ_SEARCH # for discovering and using bind-mounted network namespaces
            - CAP_NET_ADMIN   # to configure network interface capturing
            - CAP_NET_RAW     # for, erm, well, capturing?
        # Essential, as we need the full PID view in order to make nsenter do
        # its job.
        pid: host
        networks:
            00-default:
                priority: 200
            99-ghost-in-da-box:
                priority: 100
networks:
    # this is the usual the project's default network, for which ports can be
    # exposed.
    00-default:
        name: packetflix_default
    # host-internal network without any exposed ports.
    99-ghost-in-da-box:
        name: ghost-in-da-box
        internal: true
